name: Kiem Tra Code Tu Dong

on:
  pull_request:
    branches: [ "main" ] # Tự động chạy khi có PR gửi vào nhánh main

jobs:
  build_and_test: # Đây là tên của Job kiểm tra (Rất quan trọng)
    name: Build and Test Project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test with Maven
      run: mvn -B package --file pom.xml
